settings_json = { 
  "Cursor size": 1,
  "In-game interface": True,
  "Show scoreboard": True,
  "Background dim": 90,
  "Always show key overlay": True,
  "Automatic cursor size": False,
  "Score meter size": 1.25,
  "Song volume": 50,
  "Effect volume": 100,
  "Ignore beatmap hitsounds": True,
  "Use skin's sound samples": True,
  "Global leaderboard": True,
  "Mods leaderboard": "*",
  "api key": "25e80346ecb4a6a43e6262b1f39f3eb13b71d456",
  "Rotate sliderball": False,
}
